apiVersion: apps/v1
kind: Deployment
metadata:
  name: reverseproxy
spec:
  replicas: 1
  selector: 
    matchLabels:
      run: reverseproxy
  template:
    metadata:
      labels:
        run: reverseproxy
    spec:
      containers:
      - name: reverseproxy
        image: docker.io/chimezdev/udagram-reverseproxy:v1
        ports:
        - containerPort: 8080         
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m       

---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: reverseproxy
  name: reverseproxy
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    service: reverseproxy
