language: node_js
node_js:16

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  #- docker-compose -f docker-compose-build.yaml build
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t udagram-reverseproxy ./udagram-reverseproxy
  - docker tag udagram-api-user chimezdev/udagram-api-user:v3
  - docker tag udagram-api-feed chimezdev/udagram-api-feed:v3
  - docker tag udagram-frontend chimezdev/udagram-frontend:v3
  - docker tag udagram-reverseproxy chimezdev/udagram-reverseproxy:v3

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push chimezdev/udagram-api-user:v3
  - docker push chimezdev/udagram-api-feed:v3
  - docker push chimezdev/udagram-frontend:v3
  - docker push chimezdev/udagram-reverseproxy:v3
  